### ISSUE TITLE
Problems to findo config file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [viniciusbig/tvleg#1]
```
What steps will reproduce the problem?
1. $ ./tvleg.py -c
Clearing cache file
Traceback (most recent call last):
  File "./tvleg.py", line 388, in <module>
    Application()
  File "./tvleg.py", line 312, in __init__
    Downloader().clear()
  File "./tvleg.py", line 175, in clear
    pickle.dump( {}, open( self.config, "wb" ) )
IOError: [Errno 2] No such file or directory: './data/config'

2.  $ ./tvleg.py -f 
/tmp/Popcorn-Time/92dec1f14fdecac8abff0a4ad5b5e358ab2f1c7c/Game.of.Thrones.S04E1
0.720p.HDTV.x264-KILLERS.mkv 

Querying legendas.tv for Game.of.Thrones.S04E10.720p.HDTV.x264-KILLERS.mkv
Terms: game of thrones s04e10 killers
24 subtitles found. It can take a while to download it all.
Retrieving URL http://legendas.tv/downloadarquivo/539effead2610
Traceback (most recent call last):
  File "./tvleg.py", line 388, in <module>
    Application()
  File "./tvleg.py", line 319, in __init__
    if self.s.search():
  File "./tvleg.py", line 266, in search
    if self.d.get(url):
  File "./tvleg.py", line 155, in get
    self.save()
  File "./tvleg.py", line 178, in save
    pickle.dump( self.cache, open( self.config, "wb" ) )
IOError: [Errno 2] No such file or directory: './data/config'



What version of the product are you using? On what operating system?
GNU/Linux Mint



```

Original issue reported on code.google.com by `sidneica...@gmail.com` on 7 Oct 2014 at 4:18

**Comment by viniciusbig** [comment]
In certain SO we have to create a `data` folder so the script can create the config file.
I'll add that check on the code soon.

**Comment by viniciusbig** [comment]
It's fixed on develop branch. 
It will be released soon.
