### ISSUE TITLE
Error trying to search

### ISSUE THREAD

**Issue by salsa2k** [viniciusbig/tvleg#3]
Hi, I'm getting this error when I run

`python tvleg.py --dir /mnt/vdb/download/ --ignore
`

Error:
`Querying legendas.tv for The Big Bang Theory - S09E24 - The Convergence Convergence.mkv
Terms: the big bang theory s09e24 the convergence convergence

24 subtitles found. It can take a while to download it all.

Retrieving URL http://legendas.tv/downloadarquivo/57952f73396dda5016375c4a8cfad21a
Traceback (most recent call last):
  File "tvleg.py", line 451, in <module>
    Application()
  File "tvleg.py", line 378, in **init**
    if self.s.search():
  File "tvleg.py", line 316, in search
    if self.d.get(url):
  File "tvleg.py", line 201, in get
    patoolib.extract_archive(file, outdir=self.tmpFolder, verbosity=-1)
  File "/usr/local/lib/python2.7/dist-packages/patoolib/**init**.py", line 684, in extract_archive
    return _extract_archive(archive, verbosity=verbosity, interactive=interactive, outdir=outdir, program=program)
  File "/usr/local/lib/python2.7/dist-packages/patoolib/__init__.py", line 484, in _extract_archive
    run_archive_cmdlist(cmdlist, verbosity=verbosity)
  File "/usr/local/lib/python2.7/dist-packages/patoolib/__init__.py", line 421, in run_archive_cmdlist
    return util.run_checked(cmdlist, verbosity=verbosity, **runkwargs)
  File "/usr/local/lib/python2.7/dist-packages/patoolib/util.py", line 227, in run_checked
    raise PatoolError(msg)
patoolib.util.PatoolError: Command `['/usr/bin/unrar', 'x', '--', '/tmp/tmpFluL2h']' returned non-zero exit status 1
`

**Comment by salsa2k** [comment]
I found the problem.
In ubuntu if you are using unrar-free you will get some problems.
So first uninstall unrar-free:
`sudo apt-get remove unrar-free`

then add the multiverse repo
`sudo add-apt-repository multiverse`

then install unrar
`sudo apt-get update
sudo apt-get install unrar`

;)
